import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import 'primeflex/primeflex.css';
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.min.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';

//WHY do component libs do this 🥲
import 'react-date-range/dist/styles.css'; // main style file
import 'react-date-range/dist/theme/default.css'; // theme css file

//Components
import Navbar from '../components/Layout/NavigationBar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{ top: '125px' }} className={`${inter.className} relative`}>
          {children}
        </div>
      </body>
    </html>
  );
}
